services:
  database:
    image: mariadb:latest
    restart: always
    container_name: mariadb-dev
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_INIT_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./docker/volumes/data:/var/lib/mysql
    healthcheck:
      interval: 10s
      retries: 10
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      timeout: 10s
    networks:
      - default

networks:
  default:
    driver: bridge
