services:
  database:
    image: mariadb:latest
    restart: always
    container_name: mariadb-dev
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_INIT_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./docker/volumes/data:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge
